### ISSUE TITLE
Problem with separateLeadStereoParam.py

### ISSUE THREAD

**Issue by devops85** [wslihgt/separateLeadStereo#1]
Hi Team,
I am using python 2.7 and I can not execute your script. When I put:
python separateLeadStereoParam.py file.wav

The following message appears:
TypeError: main() takes exactly 2 arguments (0 given)

could you please help me?

Thanks in advance

**Comment by wslihgt** [comment]
Hi devops85,

Indeed, there was a little bug, there. I modified the `main` function, and it should work now. Let me know!

As for the actual error that I just corrected: for some reason, I added these arguments for the `main` function. Probably to be able to call it directly, passing the arguments directly instead of expecting them from the command line. For now, I revert it back to the old way, we ll have to give a better thought to it later.

Hope that helps! Tell me if this solved your issue, so I can close this issue.
Jean-Louis

**Comment by devops85** [comment]
Hi Jean-Louis,
Thank you very much for your reply. 
Well, I've downloaded the latest version of your script, and now seems to be working about arguments, but Im facing the following error message when I try to use it:

C:\SeparateLeadStereo>python separateLeadStereoParam.py sample.wav
Writing the different following output files:
    separated lead          in sample_lead.wav
    separated accompaniment in sample_acc.wav
    separated lead + unvoc  in sample_lead_VUIMM.wav
    separated acc  - unvoc  in sample_acc_VUIMM.wav
    estimated pitches       in sample_pitches.txt
C:\Python27\lib\site-packages\scipy\io\wavfile.py:31: WavFileWarning: Unfamilia
 format bytes
  warnings.warn("Unfamiliar format bytes", WavFileWarning)
Some parameter settings:
    Size of analysis windows:  2048
    Hopsize:  256.0
    Size of Fourier transforms:  2048
    Number of iterations to be done:  30
    Number of elements in WM:  40.0

I dont know what is going wrong. I've used ffmpeg to convert an mp3 music to wav in order to use it with your script. 
Does your script have any requeriment about the format of the file (.wav)?
Maybe we can add this validation before to run the script. 

Thanks in advance,
Gabriel.

**Comment by wslihgt** [comment]
Hi Gabriel,

That indeed seems to be an issue with the WAV file you used. Well, actually, that's due to the wav reading function, in scipy, which is less than great. I used that one instead of that of audiolab, but that was probably not a smart move (except that audiolab tends to be more difficult to install than scipy). 

Anyway, one work-around is to be sure that your WAV file is as simple as possible: by this, I mean without any "funny" chunks except the header and the data chunk. Obviously, that's not easy to generate automatically (well at least I do not know simple methods. For me, WAV files generated by [audacity](http://audacity.sourceforge.net/) are usually working fine...). 

The other way around is to modify the scipy function such that it returns the first (or the last) data chunk it finds in the file. 

First find where it is (the name of that file is wavfile.py):

```
import scipy.io.wavfile as wav
print wav.__file__
```

Then modify it (potentially as root, depending on the path) with your text editor. For my scipy version (0.10.0), you can see the `read` method between line 79 and 130 (you can check on their [github](https://github.com/scipy/scipy/blob/master/scipy/io/wavfile.py)). Replace `data` in the `else` part of the `if` chunk with anything (like `data_`) - or you can also discard that part completely, if you feel at ease with it. That is, for the first option, the original bit would be:

```
    chunk_id = fid.read(4)
    if chunk_id == asbytes('fmt '):
        size, comp, noc, rate, sbytes, ba, bits = _read_fmt_chunk(fid)
    elif chunk_id == asbytes('data'):
        data = _read_data_chunk(fid, noc, bits)
    else:
        warnings.warn("chunk not understood", WavFileWarning)
        data = fid.read(4)
        if _big_endian:
            fmt = '>i'
        else:
            fmt = '<i'
        size = struct.unpack(fmt, data)[0]
        fid.seek(size, 1)
```

Then you should replace with:

```
    chunk_id = fid.read(4)
    if chunk_id == asbytes('fmt '):
        size, comp, noc, rate, sbytes, ba, bits = _read_fmt_chunk(fid)
    elif chunk_id == asbytes('data'):
        data = _read_data_chunk(fid, noc, bits)
    else:
        warnings.warn("chunk not understood", WavFileWarning)
        data_ = fid.read(4)
        if _big_endian:
            fmt = '>i'
        else:
            fmt = '<i'
        size = struct.unpack(fmt, data_)[0]
        fid.seek(size, 1)
```

With this, the issue with reading WAV files that are "too" exotic should be lifted. Please tell me whether this solves your issue. Please also try to run the program on a WAV file exported by audacity, just to check that everything goes well there.

Best regards,
Jean-Louis

**Comment by devops85** [comment]
Hi Jean-Louis,
Thank you for your time. 
Well, I sent to your script 2 WAV files such I've generated trough Audacity from an MP3 files. With this new test the message ("Unfamiliar format bytes", WavFileWarning) does not appear anymore :)  but I am facing 2 new issues: 
1 - When I use the script with my first wav file, Python crash. 
2-  When I use the script with my 2nd file your script returns this message: 

Traceback (most recent call last):
  File "separateLeadStereoParam.py", line 1195, in <module>
    main()
  File "separateLeadStereoParam.py", line 635, in main
    window=sinebell(windowSizeInSamples), nfft=NFT)
  File "separateLeadStereoParam.py", line 138, in stft
    STFT = np.zeros([numberFrequencies, numberFrames], dtype=complex)
MemoryError

Thanks,
Reagrds.

**Comment by wslihgt** [comment]
Hi Gabriel,

> 1 - When I use the script with my first wav file, Python crash. 

Is there no log of the errors? How did you call the program: command line, with which options? 

> 2- When I use the script with my 2nd file your script returns this message:
> Traceback (most recent call last):
> File "separateLeadStereoParam.py", line 1195, in
> main()
> File "separateLeadStereoParam.py", line 635, in main
> window=sinebell(windowSizeInSamples), nfft=NFT)
> File "separateLeadStereoParam.py", line 138, in stft
> STFT = np.zeros([numberFrequencies, numberFrames], dtype=complex)
> MemoryError

For this, a potential explanation is the size of your files. The algorithm attempts to process the whole audio file at once which is not necessary, but that's easier to manage :) and it also requires a lot of memory. That is, with less than 4Go RAM, you may probably not be able to process more than 1 min. audio in one pass. For longer files, I'd advice to cut the file in segments, run the program on each of them, and put the separated segments back together after.

**Comment by devops85** [comment]
Hi Jean-Louis,

Sorry for the delay, well I've tried again your script with wav files (30 seconds) generated by Audacity and everything works fine now :). I have some cuestions, maybe you can help me:

1) is possible to generate only the file_acc_VUIMM.wav?
2) if we increment the numbers of iterations, the quality could will be better?.
3) Do you know how can I compare the wav file generated from FFMPEG and Audacity?, I want to try your script with files generated with FFMPEG library.
4) I think in file_acc_VUIMM.wav, the voices was removed very well, I think you can use it for generate some Karaoke Files, what do you think?

Thanks in advance,

Gabriel.

**Comment by wslihgt** [comment]
Hi Gabriel,

Sorry, after such a long time, I thought I should probably close that issue, if that solved the original problem (problem loading wav files). 

As for your questions, well, the use you suggest is in line with the whole idea of removing the main melody, of course, as I stated in my PhD thesis. The answers to your questions can be found, mostly, in my articles (check them on [that page](http://www.durrieu.ch/research/#publications)). 

As for FFMPEG, this is actually an issue more related with external modules for python, as I stated. Another workaround could also be to check the ["wave" module](http://docs.python.org/2/library/wave.html), or the [scikits.audiolab](http://pypi.python.org/pypi/scikits.audiolab/) which could provide more stable WAV file support than the scipy.io.wavfile module. 

Hope that helps!
